sudo: false
language: node_js
node_js:
  - "8"
  - "9"
  - "10"
matrix:
  include:
    - node_js: "8"
      env: TEST_SUITE=standard
    - node_js: "8"
      env: TEST_SUITE=coverage
env:
  - TEST_SUITE=unit
  - TEST_SUITE=integration
script: npm run-script $TEST_SUITE
